apiVersion: v1
kind: Service
metadata:
  name: {{ template "sample-rollout.fullname" . }}-preview
  labels:
    {{- include "sample-rollout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sample-rollout.selectorLabels" . | nindent 4 }}
