kind: Service
apiVersion: v1
metadata:
  name:  active-service-{{.Values.env.name}}
spec:
  selector:
    "app.kubernetes.io/instance": {{ .Release.Name }}
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080