kind: Service
apiVersion: v1
metadata:
  name: preview-service-{{.Values.env.name}}
spec:
  selector:
    app: {{ .Release.Name }}
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080