apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "helloworld.fullname" . }}
  labels:
    app: {{ template "helloworld.name" . }}
    chart: {{ template "helloworld.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: "helloworld"
  workloadRef:
    - apiVersion: apps/v1
      kind: Deployment
      name: hello-deployment-green
      selector:
        matchLabels:
          app: hello-deployment-helloworld-blue
    - apiVersion: apps/v1
      kind: Deployment
      name: hello-deployment-blue
      selector:
        matchLabels:
          app: hello-deployment-helloworld-blue
  strategy:
    blueGreen:
      activeService: {{ template "helloworld.fullname" . }}-blue
      previewService: {{ template "helloworld.fullname" . }}-green
