apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "helloworld.fullname" . }}
  labels:
    app: {{ template "helloworld.name" . }}
    chart: {{ template "helloworld.chart" . }}
    release: {{ .Release.Name }}-rollout
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: helloworld
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  strategy:
    blueGreen:
      activeService: active-service
      previewService: preview-service
      autoPromotionEnabled: false
      previewReplicaCount: 1
