apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-preview
  labels:
    app: {{ .Release.Name }}-preview
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      "app.kubernetes.io/instance": {{ .Release.Name }}
      "app": {{ .Release.Name }}-preview
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  strategy:
    blueGreen:
      activeService: active-service-{{.Values.env.name}}
      previewService: preview-service-{{.Values.env.name}}
      autoPromotionEnabled: false
      previewReplicaCount: 1
