apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "helloworld.fullname" . }}
  labels:
    app: {{ template "helloworld.name" . }}
    chart: {{ template "helloworld.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: "helloworld"
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: hello-deployment-green
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: hello-deployment-blue
  strategy:
    blueGreen:
      activeService: {{ template "helloworld.fullname" . }}-blue
      previewService: {{ template "helloworld.fullname" . }}-green
