# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
