apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: helloworld-dev
spec:
  project: default
  source:
    repoURL: "https://github.com/akashkaturi/argo-cd-helm-deployments.git"
    path: charts/helloworld
    targetRevision: HEAD
    helm:
      valueFiles: 
        - values-dev.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
