apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: helloworld-dev
spec:
  project: default
  source:
    repoURL: "https://github.com/akashkaturi/argo-cd-helm-deployments.git"
    path: charts/helloworld
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 0
        image:
          repository: akashkaturi/argofastapi
          tag: 0.3
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 80

        env:
          name: "dev"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
